
### List
GET http://localhost:8080/api/user?page=0&size=1

### Get
GET http://localhost:8080/api/user/1

### Patch
PATCH http://localhost:8080/api/user/3
Content-Type: application/json

{
    "username": "xkyii52",
    "nickname": "xkyii53",
    "password": "xk1231234"
}