
### List
GET {{url}}/api/user?page=0&size=1

### Get
GET {{url}}/api/user/1

### Patch
PATCH {{url}}/api/user/3
Content-Type: application/json

{
    "username": "xkyii52",
    "nickname": "xkyii53",
    "password": "xk1231234"
}

### Create
POST {{url}}/api/user
Content-Type: application/json

{
    "username": "xkyii5",
    "nickname": "xkyii5",
    "password": "xk1231234"
}