### test-permission
GET {{url}}/test/permitall

### test-denyall
GET {{url}}/test/denyall

### test-Authenticated
GET {{url}}/test/authenticated
Authorization: Bearer {{bearer}}

### test-rolesallowed
GET {{url}}/test/rolesallowed
Authorization: Bearer {{bearer}}