### register-注册
GET {{url}}

### exception
GET {{url}}/exception
Content-Type: application/json

### errorCode
GET {{url}}/errorCode

### validate
POST {{url}}/validate
Content-Type: application/json

{
  "username": "",
  "password": "123456",
  "code": "4",
  "uuid": "aaaabbbb443423243"
}

### cheese
GET {{url}}/cheese
