### test-permission
GET {{url}}/test/permit-all

### test-denyall
GET {{url}}/test/deny-all

### test-Authenticated
GET {{url}}/test/authenticated
Authorization: Bearer {{bearer}}

### test-rolesallowed
GET {{url}}/test/rolesallowed
Authorization: Bearer {{bearer}}