
### 登录admin
POST {{url}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123",
  "code": "2",
  "uuid": "13af4b4bcde9447885a7a556d34e67ea"
}


### getInfo
GET {{url}}/getInfo
Content-Type: application/json
#Authorization: Bearer {{token}}

### captchaImage
GET {{url}}/captchaImage