### 注册
POST {{url}}/user/register
Content-Type: application/json

{
  "username": "xkyii",
  "password": "123456",
  "code": "4",
  "uuid": "aaaabbbb443423243"
}


### 登录admin
POST {{url}}/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "epBqlhkISqOgzqy8ePae/spvVp7r3x/NZrNNSPbUlhU1QZZxyceoIUaaswzGIaRn8KZexwjJsTU6/BZvyYszBMCKPXKkyOHHPZLfDhg9UDCfnkdCm5fJznwilaLyGpBKSBCvoSrkfIibkCQoEQi0V8LmtM0SY+MZaQ640FYWe5TYqOm1/Vfd9IqngQXuFPlmXn4RUt3U4Nti4ay+hZJFxJXFrg0S8pNBUGKg8hLL2weOq0wMZa45o6scVUpxezpw/1TAbegFMNFZ0RtaJWsIJFvC1nV5C2CEuGrFLHDodsuiGkiGWh5AGB7SVEwVxFV0gqbTvzNDD/D7Il/IFmBcGA==",
  "code": "4",
  "uuid": "aaaabbbb443423243"
}

### 登录-xk1
POST {{url}}/user/login
Content-Type: application/json

{
  "username": "xk1",
  "password": "CHpQWTGKnxDXFTtf6b4SY/4NBxPSntvxm0s+I22ir3LsW8qe1zumoJVRaQm4jvKljvejhcVddfQsE3cp+6n+qzwcvVYDCwJIJonaZuQSYzCPVwIYnWJK0EWFP4qFlLxHGNVzH7B+gJcjmZ/po92saSDNXHTT0qASbr1KCBKFectdzX/3CjWQc7Y8ZrmuUSvzBBjTUTmM2BlNZtVPxmsmYZEmjTkGlnVhhuBoqKktdt/U3EMxHWRViI/oFLojqPREi4AZdgBY/i4HJv9HLI1FUgMjiKI58Ksiz4OF99rALjxsdzZo2qLZzZYltB9285qolGYN+e/MmyzVFwaxAY2LcQ=="
}

### 登录-xk2
POST {{url}}/user/login
Content-Type: application/json

{
  "username": "xk2",
  "password": "epBqlhkISqOgzqy8ePae/spvVp7r3x/NZrNNSPbUlhU1QZZxyceoIUaaswzGIaRn8KZexwjJsTU6/BZvyYszBMCKPXKkyOHHPZLfDhg9UDCfnkdCm5fJznwilaLyGpBKSBCvoSrkfIibkCQoEQi0V8LmtM0SY+MZaQ640FYWe5TYqOm1/Vfd9IqngQXuFPlmXn4RUt3U4Nti4ay+hZJFxJXFrg0S8pNBUGKg8hLL2weOq0wMZa45o6scVUpxezpw/1TAbegFMNFZ0RtaJWsIJFvC1nV5C2CEuGrFLHDodsuiGkiGWh5AGB7SVEwVxFV0gqbTvzNDD/D7Il/IFmBcGA==",
  "code": "4",
  "uuid": "aaaabbbb443423243"
}
