### register-注册
POST {{url}}/user/register
Content-Type: application/json

{
  "username": "hello",
  "password": "12345",
  "code": "4",
  "uuid": "aaaabbbb443423243"
}


### login-登录
POST {{url}}/user/login
Content-Type: application/json

{
  "username": "hello",
  "password": "ebsO1fWDmuY7INdn7zk9fxaPcs5l0nSPE6d7SZebA5icikvRb7Ue7vzhbBL/UA2zUWNOk5XGcDm6w2AruCol3Qi15omOwPywsyI/rD4Mc/qvT6hWzkRjhvG3Kr/iil7Uo+uIVHKih/mdYfMhwEd6o3+yrNHA5N0Nt0CH8LyY5AEldNEUA1RGua0JP8MsCeJMrlWimmb4krqK8PZYoRVxGFHxRxAvDylQ2jgTmte97/DrgDMCZIiNj7optdAA5ZTZBfyzg9aK5EOkSGnWBhB3/tbk6COysvZfYZH9Dp9YdnxU2QjDeCOTp0W37gVNaqEEFDxbtsXRL2ljdgZNzkhXPA==",
  "code": "4",
  "uuid": "aaaabbbb443423243"
}
