### register-注册
POST {{url}}/user/register
Content-Type: application/json

{
  "username": "hello",
  "password": "12345",
  "code": "4",
  "uuid": "aaaabbbb443423243"
}


### login-登录
POST {{url}}/user/login
Content-Type: application/json

{
  "username": "hello",
  "password": "1",
  "code": "4",
  "uuid": "aaaabbbb443423243"
}
